### ISSUE TITLE
Issues on ARM

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#82] opened 2021-11-09 17:11 UTC
Tried building yarr for raspberry pi as per the instruction and got build successful however while try to run got the error:  
`-bash: ./yarr: cannot execute binary file: Exec format error` 

Then changed `GOARCH=amd64` to `GOARCH=armv7` in makefile and got issue(s) while build
`mkdir -p _output/linux
GOOS=linux GOARCH=armv7 go build -tags "sqlite_foreign_keys release linux" -ldflags="-s -w -X 'main.Version=2.1' -X 'main.GitHash=f98de9a0'" -o _output/linux/yarr src/main.go
cmd/go: unsupported GOOS/GOARCH pair linux/armv7
make: *** [makefile:21: build_linux] Error 2
`

Guide me how to resolve this, thanks.

**Comment by nkanaev** [comment] 2021-11-10 10:08
```
$ GOOS=linux GOARCH=arm GOARM=7 go build ...
```

is what you probably need.

see here: https://github.com/golang/go/wiki/GoArm

**Comment by tillcash** [comment] 2021-11-11 06:52
Thanks, I'm able to build it. While running ./yarr -addr 0.0.0.0:7070 it shows empty page when try to access from Laptop

```
2021/11/11 12:16:10 main.go:86: using db file /home/pi/.config/yarr/storage.db
2021/11/11 12:16:10 migration.go:28: db version is 0. migrating to 6
2021/11/11 12:16:10 migration.go:37: [migration:1] starting
2021/11/11 12:16:10 migration.go:53: [migration:1] done
2021/11/11 12:16:10 migration.go:37: [migration:2] starting
2021/11/11 12:16:10 migration.go:53: [migration:2] done
2021/11/11 12:16:10 migration.go:37: [migration:3] starting
2021/11/11 12:16:10 migration.go:53: [migration:3] done
2021/11/11 12:16:10 migration.go:37: [migration:4] starting
2021/11/11 12:16:10 migration.go:53: [migration:4] done
2021/11/11 12:16:10 migration.go:37: [migration:5] starting
2021/11/11 12:16:10 migration.go:53: [migration:5] done
2021/11/11 12:16:10 migration.go:37: [migration:6] starting
2021/11/11 12:16:10 migration.go:53: [migration:6] done
2021/11/11 12:16:10 main.go:133: starting server at http://0.0.0.0:7070
```
Is got stuck at `starting server at http://0.0.0.0:7070`.

**Comment by nkanaev** [comment] 2021-11-11 09:46
logs seem pretty normal. that means the server has started properly.

sorry, cannot help with the access issues without further information.

**Comment by tillcash** [comment] 2021-11-12 10:06
Sorry to bother you, unfortunately I don't know how to get more information.

Tried compiling from laptop with value `GOOS=linux GOARCH=arm GOARM=7 go build -tags "sqlite_foreign_keys release linux" -ldflags="$(GO_LDFLAGS)" -o _output/linux/yarr src/main.go`  in `makefile` and getting
```
2021/11/12 15:27:24 main.go:86: using db file /home/pi/.config/yarr/storage.db
2021/11/12 15:27:24 migration.go:28: db version is 0. migrating to 6
2021/11/12 15:27:24 migration.go:37: [migration:1] starting
2021/11/12 15:27:24 migration.go:63: [migration:1] failed to start transaction
2021/11/12 15:27:24 main.go:114: Failed to initialise database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```
Even though the value `CGO_ENABLED=1` already set in `makefile`.

**Comment by nkanaev** [comment] 2021-11-12 10:11
if you're directly running the command, you'd need to add env variable too:

```
$ CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 go build ...
```

**Comment by tillcash** [comment] 2021-11-12 12:43
```
[me@archlinux yarr]$ make build_linux
mkdir -p _output/linux
CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 go build -tags "sqlite_foreign_keys release linux" -ldflags="-s -w -X 'main.Version=2.1' -X 'main.GitHash=1ad693f9'" -o _output/linux/yarr src/main.go
# runtime/cgo
gcc: error: unrecognized command-line option '-marm'; did you mean '-mabm'?
make: *** [makefile:21: build_linux] Error 2
```

**Comment by tillcash** [comment] 2021-11-12 13:12
If I build from raspberry pi it will get build but while run getting `204 No Content`.
```
[me@archlinux ~]$ wget http://192.168.1.200:7070
--2021-11-12 18:36:03--  http://192.168.1.200:7070/
Connecting to 192.168.1.200:7070... connected.
HTTP request sent, awaiting response... 204 No Content
2021-11-12 18:36:03 (0.00 B/s) - ‘index.html’ saved [0]
```
```
pi@raspberrypi:~ $ wget http://127.0.0.1:7070
--2021-11-12 18:40:02--  http://127.0.0.1:7070/
Connecting to 127.0.0.1:7070... connected.
HTTP request sent, awaiting response... 204 No Content
2021-11-12 18:40:02 (0.00 B/s) - ‘index.html’ saved [0]
```

I have tried everything up to my knowledge.

**Comment by fenuks** [comment] 2022-05-23 09:28
I have same issue trying to run yarr on ARM-based OpenWRT router built with

```sh
CC=arm-linux-musleabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 go build -tags "sqlite_foreign_keys release linux" -ldflags="$(GO_LDFLAGS)" -o _output/openwrt/yarr src/main.go
```

It runs, but returns 204 No Content. Regular x86_64 Linux version returns page contents.

**Comment by nkanaev** [comment] 2022-05-31 16:25
Unfortunately I don't have an ARM hardware to test it on.

**Comment by fenuks** [comment] 2022-05-31 16:39
I've been trying to figure it out myself, but so far, I was unable to get it working. I have ARM router that I would like to run yarr on (it has pleasant web guit, and so far is most lightweight RSS self-hosting solution I stumbled upon – my preliminary testing shows ~70 MB RAM usage on x86_64 PC which is fine even for constrained router hardware). But back to the issue.

I think problem might be caused by cross-compiling. Author of this ticket was also cross-compiling. I happen to have Pinebook Pro, and it's possible to compile yarr there directly, and it's working as expected. In order to confirm my hypothesis, I want to configure /overlay on my router, so I could install go toolchain, and compile yarr directly on the device (I don't have enough space on rootfs to install golang compiler and gcc, but I have external drive attached).

Probably it could be also possible to cross-compile yarr to run it on the phone, assuming it has ARM processor, and runs Android or any other OS that allows to run own binaries.

**Comment by fenuks** [comment] 2022-05-31 18:14
Compiling yarr directly on the device doesn't help. Same error.

Perhaps issue is related to the fact that OpenWRT uses musl? It doesn't compile cleanly, I had to manually remove some flags like `-lpthread` because musl has it builtin, and Pinebook Pro uses glibc.

**Comment by nkanaev** [comment] 2022-06-01 12:32
I've created an initial draft of a dockerfile to cross-compile to ARM. see the instructions here: https://github.com/nkanaev/yarr/blob/master/build.md.

It currently compiles only to ARM64, but can easily be extended to support 32-bit architecture processors. Happy to help out with adding the support for these.

Would appreciate if someone could test out whether the binaries work.

**Comment by fenuks** [comment] 2022-06-01 16:51
I've tested your dockerfile and building for aarch64 works fine. Binary runs correctly in qemu, and on a real aarch64 hardware.

I adapted it for arm7h, and produced binary has this 204 problem.

```
FROM ubuntu:20.04

# Install GCC
RUN apt update
RUN apt install -y \
        wget build-essential \
        gcc-arm-linux-gnueabihf \
        binutils-arm-linux-gnueabihf binutils-arm-linux-gnueabihf-dbg
RUN env DEBIAN_FRONTEND=noninteractive \
    apt install -y qemu-user qemu-user-static

# Install Golang
RUN wget --quiet https://go.dev/dl/go1.18.2.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf go1.18.2.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

# Copy source code
WORKDIR /root/src
RUN mkdir /root/out
COPY . .

# Build ARM64
RUN env \
        CC=arm-linux-gnueabihf-gcc \
        CGO_ENABLED=1 \
        GOOS=linux GOARCH=arm GOARM=7 \
    go build \
        -tags "sqlite_foreign_keys release linux" \
        -ldflags="-s -w" \
        -o /root/out/yarr.arm7 src/main.go

CMD ["/bin/bash"]
```

You can run binary with `qemu-arm -L /usr/arm-linux-gnueabihf/ yarr.arm7`, and hopefully you will get

```
root@753ca5491d79:~/src# wget http://127.0.0.1:7070
--2022-06-01 16:44:42--  http://127.0.0.1:7070/
Connecting to 127.0.0.1:7070... connected.
HTTP request sent, awaiting response... 204 No Content
2022-06-01 16:44:42 (0.00 B/s) - 'index.html.1' saved [0]
```

So, I suppose error is somewhat related to arm7 architecture (my router has it, and Pinebook Pro that runs yarr just fine has aarch64 CPU). My guess that musl might be cause is incorrect, I verified it building yarr on Alpine Linux (works well).

**Comment by nkanaev** [comment] 2022-06-01 19:56
There was a bug in the url routing mechanism (similar to the one mentioned [here](https://github.com/golang/go/issues/47447)). [The fix](https://github.com/nkanaev/yarr/commit/cba3fbc48ce0d1dbb609b48016573d0299451377) has landed on master, was tested via qemu.

I've updated `dockerfile.arm` to build both ARM64 & ARMv7 binaries.

**Comment by fenuks** [comment] 2022-06-01 22:31
Thank you for very quick fix – problem is gone, yarr is working correctly on my ARMv7 router.

**Closed** 2022-06-01 22:32 UTC
Labels: help wanted
