### ISSUE TITLE
Nil pointer issue

### ISSUE THREAD

**Issue by minioin** [nkanaev/yarr#5] opened 2020-09-15 17:25 UTC
I tried running this service with more than 300 links and out of three times, it crashed twice.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x89bd17]

goroutine 24 [running]:
github.com/nkanaev/yarr/server.findFavicon(0xc000406ba0, 0x1c, 0xc0002d1260, 0x29, 0x0, 0x0, 0x0)
	/var/home/minioin/workspace/yarr/server/crawler.go:170 +0x5d7
github.com/nkanaev/yarr/server.(*Handler).startJobs.func2()
	/var/home/minioin/workspace/yarr/server/server.go:76 +0x3aa
created by github.com/nkanaev/yarr/server.(*Handler).startJobs
	/var/home/minioin/workspace/yarr/server/server.go:97 +0x149
```

**Comment by nkanaev** [comment] 2020-09-15 19:22
would you be able to discover the feed links on which it crashes? if not, may i ask you to provide your opml file?

**Comment by minioin** [comment] 2020-09-16 05:40
I'll keep an eye for it. Can't share the opml. Sorry.

**Comment by nkanaev** [comment] 2020-09-16 09:45
i've added logging for favicon search: https://github.com/nkanaev/yarr/commit/2d629dddadc67b33545109e3125be5eaec6203f4.

would you be able to reproduce it? if the issue disappeared, you might need to start afresh either by:
* creating a new docker instance
* moving the db file (`$XDG_CONFIG_HOME/yarr/storage.db` or `$HOME/.config/yarr/storage.db` on Linux) elsewhere, restarting the server & importing from scratch

the log message prior to the crash should reveal the feed responsible for the cause.

**Comment by minioin** [comment] 2020-09-18 12:18
2020/09/18 18:00:38 server.go:78: searching favicon for: https://www.cncf.io https://www.cncf.io/feed/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x89bd17]

goroutine 37 [running]:
github.com/nkanaev/yarr/server.findFavicon(0xc00058a680, 0x19, 0xc00058a6a0, 0x1e, 0x0, 0x0, 0x0)
	/var/home/minioin/workspace/yarr/server/crawler.go:170 +0x5d7
github.com/nkanaev/yarr/server.(*Handler).startJobs.func2()
	/var/home/minioin/workspace/yarr/server/server.go:79 +0x490
created by github.com/nkanaev/yarr/server.(*Handler).startJobs
	/var/home/minioin/workspace/yarr/server/server.go:100 +0x149

**Comment by minioin** [comment] 2020-09-18 12:20
2020/09/18 18:03:47 server.go:78: searching favicon for: https://www.androidcentral.com/ http://feeds.androidcentral.com/androidcentral
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x89bd17]

goroutine 13 [running]:
github.com/nkanaev/yarr/server.findFavicon(0xc0003d7a40, 0x1d, 0xc0003a8c60, 0x30, 0x0, 0x0, 0x0)
	/var/home/minioin/workspace/yarr/server/crawler.go:170 +0x5d7
github.com/nkanaev/yarr/server.(*Handler).startJobs.func2()
	/var/home/minioin/workspace/yarr/server/server.go:79 +0x490
created by github.com/nkanaev/yarr/server.(*Handler).startJobs
	/var/home/minioin/workspace/yarr/server/server.go:100 +0x149

**Comment by minioin** [comment] 2020-09-18 12:21
It's quite easy to trigger this that I remember it now. Import a large opml file and then start searching for keyterms while it is still updating. BAM! You've got this error and can occur on any feed url.

**Comment by nkanaev** [comment] 2020-10-02 15:50
fixed in https://github.com/nkanaev/yarr/commit/6222761dd3b6058f6c6a37db76785fcf9d47ffa5

**Closed by nkanaev** 2020-10-02 15:50 UTC
Labels: bug
