### ISSUE TITLE
Articles added to the wrong feed

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#110] opened 2022-08-23 18:06 UTC
Sometimes if I add the same feed twice unknowingly, the contents get appended it to random feed.

![Screenshot_20220823_232649](https://user-images.githubusercontent.com/19629778/186230989-2840df29-c63b-4b6b-a33a-689dbfe270f7.png)

Tried to add the feed `https://audioboom.com/channels/4959898.rss` it got into the feed `https://www.theregister.com/security/patches/headlines.atom`. 

I have faced the same issue a few times randomly.

![image](https://user-images.githubusercontent.com/19629778/186229680-7b1c9c1f-1856-4321-b403-262c542d8752.png)

**Comment by nkanaev** [comment] 2022-08-30 08:52
hi @tillcash 

was the binary compiled manually? if that's the case, the missing `sqlite_foreign_keys` (foreign key constrain enforcement) feature might be the reason of the issue.

**Comment by tillcash** [comment] 2022-08-30 10:13
@nkanaev, thanks for the reply.

Using the docker image by @arsfeld which has 10k+ pulls.
https://hub.docker.com/r/arsfeld/yarr

**Comment by nkanaev** [comment] 2022-08-30 15:54
interesting. what version are you using?

**Comment by tillcash** [comment] 2022-08-30 16:10
Tag [v2.3](https://hub.docker.com/layers/yarr/arsfeld/yarr/v2.3/images/sha256-64ac2d932977fb019d68c28696d3ac839d0abfc80e6474ec76c8ec1ac06aa075?context=explore)

**Comment by tillcash** [comment] 2022-08-30 16:44
I'm not sure whether it's expected behavior.

If I press the arrow up or down key in the unread or started tab, it navigates to the next feed as per the All column instead of navigating to the next unread or started feed.

**Comment by nkanaev** [comment] 2022-09-27 19:32
sorry for the late reply.

> Sometimes if I add the same feed twice unknowingly...

I tried adding the same feed multiple times, and got the "FOREIGN KEY constrain failed" messages too. It doesn't affect the functionality, and can be safely ignored. You may get duplicate entries occasionally, but that's the nature of the feeds (see https://github.com/nkanaev/yarr/issues/67).

> ...the contents get appended it to random feed.
> Tried to add the feed https://audioboom.com/channels/4959898.rss it got into the feed https://www.theregister.com/security/patches/headlines.atom.

That's very strange. But unfortunately I couldn't reproduce it with the local build. I'll keep the ticket open until the issue gets resolved.

> If I press the arrow up or down key in the unread or started tab, it navigates to the next feed as per the All column instead of navigating to the next unread or started feed.

That's an accidental "feature". The supported feed navigation shortcut is via `H`/`L` keys. Making arrow navigation properly usable would be nice, but I'm too lazy to implement it right now.

**Comment by nkanaev** [comment] 2023-02-09 22:03
> Sometimes if I add the same feed twice unknowingly, the contents get appended it to random feed.

@tillcash are you still experiencing the issue? I couldn't reproduce the issue you've described in the latest release, neither in the local nor the docker setup.

If there's no clear reproduction steps, I'm unable to help with the issue, and would have to close the ticket.

**Comment by nkanaev** [comment] 2023-02-10 09:44
> Yarr capture Alt + 1 to 3 keyboard shortcut interfere with Firefox and hinder productivity.

fixed in https://github.com/nkanaev/yarr/commit/0f6d4d639d82d7a4a9d8bb580d6b17abd738f706. thanks for the mention.

**Closed by nkanaev** 2023-02-10 09:44 UTC
